### ISSUE TITLE
Catherine: Full Body has a serious bug

### ISSUE THREAD

**Issue by tazevam** [Ryujinx/Ryujinx#1940]
## Bug Report
The graphics problems fix in new version.
but it still has a serious bug，so the game cannot continue.
![4](https://user-images.githubusercontent.com/73407337/105256949-b6493980-5bc1-11eb-8de0-480af33cfa43.PNG)

### What's the issue you encountered?
In stage 1, When you reach the position in the picture and pull out the stone, the character can’t grab the edge of the stone and fall down. on real machine, he can grab the edge between two stones and move to the next place.
![3](https://user-images.githubusercontent.com/73407337/105209273-9fd0bd00-5b84-11eb-9d30-37530f35c6f8.PNG)

emulator
![2](https://user-images.githubusercontent.com/73407337/105198981-35fee600-5b79-11eb-91a1-1101c64b42ef.PNG)

real machine
![1](https://user-images.githubusercontent.com/73407337/105198820-0a7bfb80-5b79-11eb-89ab-41c4e8acbc49.PNG)

### How can the issue be reproduced?

Just started.

### Log file
[Ryujinx_1.0.6348_2021-01-20_22-28-05.log](https://github.com/Ryujinx/Ryujinx/files/5843601/Ryujinx_1.0.6348_2021-01-20_22-28-05.log)

### Environment?
- Ryujinx version: 1.0.6348
- Game version: 1.0.0

- System Specs:
  - OS: Windows 10
  - CPU: I3-8350k
  - GPU: NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : [ No ]

### Additional context?
thank for the hardwork!

**Comment by GamerzHell9137** [comment]
https://github.com/Ryujinx/Ryujinx-Games-List/issues/1926

**Comment by tazevam** [comment]
> [Ryujinx/Ryujinx-Games-List#1926](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1926)

it fix in new version（720p）
![3](https://user-images.githubusercontent.com/73407337/105203545-35b51980-5b7e-11eb-8a8f-39adaca237e4.PNG)

**Comment by AcK77** [comment]
I suggest you to report the rendering issue in https://github.com/Ryujinx/Ryujinx-Games-List/issues/1926 instead of here.
Thanks.

**Comment by tazevam** [comment]
> I suggest you to report the rendering issue in [Ryujinx/Ryujinx-Games-List#1926](https://github.com/Ryujinx/Ryujinx-Games-List/issues/1926) instead of here.
> Thanks.

Ok, edited

**Comment by gdkchan** [comment]
Going to re-open this to track the CPU bug.

**Comment by tazevam** [comment]
> Going to re-open this to track the CPU bug.

Confirm that the problem is fixed in [1.0.6383](https://github.com/Ryujinx/Ryujinx/pull/1943),
![5](https://user-images.githubusercontent.com/73407337/105329394-1238b000-5c0c-11eb-8b37-0c792b5fea0f.PNG)
![7](https://user-images.githubusercontent.com/73407337/105329437-1e247200-5c0c-11eb-8e09-c27129c4e75a.PNG)

Although there is a slight texture problem, but game can continue. thx
![8](https://user-images.githubusercontent.com/73407337/105330609-78720280-5c0d-11eb-8736-d868fe11427c.PNG)

**Comment by tazevam** [comment]
In the latest version (1.0.6438), this bug has reappeared.

**Comment by EmulationFanatic** [comment]
@tazevam the fix has not been merged to master yet.

**Comment by tazevam** [comment]
> @tazevam the fix has not been merged to master yet.

ok, I will wait and continue to use 6382

**Comment by EmulationFanatic** [comment]
The issue is not resolved because, as previously explained, the fix it not yet in master.
