### ISSUE TITLE
Multiple games broken since 1.1.107

### ISSUE THREAD

**Issue by F1ReB4LL** [Ryujinx/Ryujinx#3641]
Since the original issue was closed by its author and all the subissues were ignored, I'm moving them into this new issue.

### What's the issue you encountered?

Ryujinx 1.1.107 and its infamous PR https://github.com/Ryujinx/Ryujinx/pull/3302 have broken a number of games, some of them were fixed by https://github.com/Ryujinx/Ryujinx/pull/3610, some were not.

Shadow Gangs (1.1.106) - works fine
Shadow Gangs (1.1.107) - either crashes on the first logo or goes ingame with crazy flickering, better described here - https://github.com/Ryujinx/Ryujinx-Games-List/issues/3270

Disjunction (1.1.106) - works fine:
![ryujinx_disj11106](https://user-images.githubusercontent.com/39680140/185744249-db2b28bf-deac-49f8-9372-0ba2bc167505.png)
Disjunction (1.1.107) - Many sprites are covered with cyan rectangles:
![ryujinx_disj11107](https://user-images.githubusercontent.com/39680140/185744254-6d82d792-0b85-44dc-b132-49688c440812.png)
Disjunction (1.1.233 OpenGL) - Many sprites are covered with cyan rectangles:
![ryujinx_disj11233ogl](https://user-images.githubusercontent.com/39680140/186854078-f6f9451a-7974-4c68-99ba-38b4e21e31c0.png)
Disjunction (1.1.233 Vulkan) - no cyan rectangles, but some sprites are cut the same way as if they were covered (look at the bodies):
![ryujinx_disj11233vlk](https://user-images.githubusercontent.com/39680140/186854008-f7231fa1-7c62-4bb6-abf5-61c3aed82001.png)

Aggelos (1.1.106) - the main menu is rendered fine, both "Adventure" and "Options" words are visible:
![ryujinx_agg11106](https://user-images.githubusercontent.com/39680140/185746423-d0f0afce-5380-4c3d-854e-810384d0f171.png)
Aggelos (1.1.107) - the word "Options" is rendered invisible:
![ryujinx_agg11107](https://user-images.githubusercontent.com/39680140/185746429-fa58a468-9e61-4f85-83de-b90d87460da1.png)
Aggelos (1.1.233 OpenGL) - the word "Options" is rendered invisible:
![ryujinx_agg11233ogl](https://user-images.githubusercontent.com/39680140/186854151-05eedc90-c3ef-4186-ace0-d1e498c627a8.png)
Aggelos (1.1.233 Vulkan) - the word "Options" is rendered invisible:
![ryujinx_agg11233vlk](https://user-images.githubusercontent.com/39680140/186854126-2439e8c4-8cee-42ef-8108-72199a2a3ecf.png)

### How can the issue be reproduced?

Launch the above-mentioned titles on Ryujinx version 1.1.107 or newer. 1.1.106 and earlier are not affected.

### Environment?

- Ryujinx version: 1.1.107, 1.1.233</br>
- Game version: 1.0.0 (Shadow Gangs), 1.0.1 (Disjunction), 1.0.2 (Aggelos)</br>
- System Specs:
  - OS: *Windows 10 21H2*
  - CPU: *i5-11400H*
  - GPU: *NVIDIA RTX 3050*
  - RAM: *24GB*
- Applied Mods : [ No ]

**Comment by EmulationFanatic** [comment]
> Since the original issue was closed by its author and all the subissues were ignored, I'm moving them into this new issue.
> 
The original issue was for Blossom Tales II regressing.
It was fixed. That's why it was closed.

**Comment by EmulationFanatic** [comment]
There's no way to know the entirety of negatively affected games by a particular PR. As you have seen, fixing one game that regressed doesn't necessarily fix all games that regressed. Some PRs have one small change; others have wide, sweeping changes, any small part of which could cause a regression in one game, while another part of the change might affect a different game.
For this and other reasons, reporting individual regressions as they are discovered is exactly how it should be handled.

**Comment by gdkchan** [comment]
Can someone check if #4284 fixes those issues?

**Comment by F1ReB4LL** [comment]
> Can someone check if #4284 fixes those issues?

Aggelos fixed.

![ryujinx11553_agg1](https://user-images.githubusercontent.com/39680140/219950903-9a5a5286-d447-425e-8cce-62394509501c.png)
![ryujinx11553_agg2](https://user-images.githubusercontent.com/39680140/219950910-dd340633-ec8b-4f46-a603-7f0754ee83ff.png)

Shadow Gangs and Disjunction still broken, sadly.

![ryujinx11553_disj1](https://user-images.githubusercontent.com/39680140/219951031-8feb6582-7e6d-47d9-86cf-d3f9e984a036.png)
![ryujinx11625_disj2](https://user-images.githubusercontent.com/39680140/219951549-ac3112d1-532d-4726-9c2f-4aaea09b4d6a.png)

**Comment by F1ReB4LL** [comment]
https://github.com/Ryujinx/Ryujinx/issues/4448 - a related issue (though, caused by a more recent PR https://github.com/Ryujinx/Ryujinx/pull/3610, not 3302), but still a part of the same problem.

**Comment by nsklaus** [comment]
i'm experiencing font rendering issues as well. in skyrim. the problem is not immediately visible, at first everything is rendered correctly. it is needed to play for some time, maybe 15-30minutes, but the problem will always show up after some time. here's a screenshot:
![Screenshot 2023-02-28 at 15 24 20](https://user-images.githubusercontent.com/6810861/221884541-dea60406-b509-47f7-ab31-7e3f1f10add4.png)

**Comment by riperiperi** [comment]
This could be a different issue entirely. Can you verify that this issue appeared with #3302?

**Comment by nsklaus** [comment]
> This could be a different issue entirely. Can you verify that this issue appeared with #3302?

could you tell me how do you think i could confirm that ?
by the way, i'm using my own build on macos (macbookpro m2 pro) and beside using the current tree, not the macos1 build from november, and i also have imported the following PR in my local tree:
  pr4368
  pr4404
  pr4406
  pr4408
  pr4471
just for being clear about my environment.

**Comment by riperiperi** [comment]
I guess you can't test that on macos, since the game won't work back then. It's also possible that this bug is macos specific, you'd probably need to test the older version on windows (and the latest for good measure).

**Comment by nsklaus** [comment]
unfortunately i do not have access to a windows machine, and ryujinx cannot run in virtual machine either.

**Comment by F1ReB4LL** [comment]
Both Shadow Gangs and Disjunction were fixed by https://github.com/Ryujinx/Ryujinx/pull/6687
