### ISSUE TITLE
(All operating systems) - V-Sync/framerate synchronization not working correctly

### ISSUE THREAD

**Issue by greybaron** [Ryujinx/Ryujinx#3906]
#### Overview:
- At the moment, it appears that the presentation of rendered frames is not properly synced to the display's refresh rate.
- Therefore, a game that outputs a stable 60 FPS will still look noticably stuttery, as if dropping frames.

#### Smaller Details: 
- This issue occurs on all tested refresh rates: 59.94/60/120 Hz (internal "ProMotion" display); or 60 Hz (external display)
- It occurs on both tested games (Fast RMX or Super Mario Odyssey). Both were tested in situations where a stable 60 FPS was effectively guaranteed. The amount of (I presume) skipped frames appeared to be very similar

#### Nature of Request:  
- Change
  - if Ryujinx has no "real" support for this at the moment, it could count as Addition

### Why would this feature be useful?
- especially 60 FPS games would benefit a lot, since at the moment they will appear quite choppy.
- Potentially, unstable framerates or 30 FPS titles could also benefit from improved framerate → refresh rate synchronization.

**Comment by riperiperi** [comment]
This actually affects all platforms, we have no way of reliably sourcing the host refresh timings, so the emulated vsync for the Guest will mismatch and can cause frame pacing issues.

There is an extension for this available on mobile, linux (mesa drivers) and moltenvk, but it is not available on any Windows drivers.

`VK_GOOGLE_display_timing`

If it were available on Windows, it would be a priority to implement.

**Comment by riperiperi** [comment]
It's also worth noting that on Windows you can kind of work around this by disabling ryu's guest vsync, then forcing vsync through your gpu driver at 60hz. Obviously this isn't ideal, as some games want a 30hz vsync (vulkan also doesn't support swap interval...) and it requires your monitor to be set to 60hz. I don't think there's a way to do this with mvk/metal.

**Comment by greybaron** [comment]
That is unfortunate. However I have noticed that at least on Windows the frame pacing is still significantly better than on macOS. Maybe there is a way to reduce the severity on macOS.

**Comment by jimbo1111** [comment]
I've noticed the same as greybaron, I get far more tearing and jittering on Mac than on windows at the moment.

I'd add to this request and suggest that some way to lock fps within Ryujinx on Mac would be good.  In windows you can do so with NVIDIA control panel, and lock fps to 45 or 60, to boost frames of 30fps games with vsync off.  Would like to be able to do this on Mac, but NVIDIA control panel does not exist, and I'm not aware of a way to lock fps unless an application offers that feature itself.

As-is, I'm either stuck at 30fps (which is ugly, makes inputs feel laggy, etc) or bouncing around between various high fps values which my 60Hz monitor can't use. A way to consistently lock fps within the app would be a useful addition that is not currently available on Mac through external sources.

**Comment by skabning** [comment]
Would a framerate limiter be a possibility? For example, in Skyward Sword, I get a perfectly smooth 60fps, but I also get horrible screen tearing. When I turn off VSync I get a buttery smooth image, but the framerate nearly doubles and everything moves at twice the speed.
This is on an M1 Macbook Air, and the performance absolutely blows my mind! It's just a shame about the screen tearing.

**Comment by tellowkrinkle** [comment]
> It's also worth noting that on Windows you can kind of work around this by disabling ryu's guest vsync, then forcing vsync through your gpu driver at 60hz. Obviously this isn't ideal, as some games want a 30hz vsync (vulkan also doesn't support swap interval...) and it requires your monitor to be set to 60hz. I don't think there's a way to do this with mvk/metal.

In Metal, if you enable vsync (through [`[CAMetalLayer setDisplaySyncEnabled:]`](https://developer.apple.com/documentation/quartzcore/cametallayer/2887087-displaysyncenabled?language=objc)) on Ventura and above, it should enforce the display's refresh rate.
On pre-Ventura, this was buggy and acted like vsync off if you used `[MTLDrawable present]` and acted like vsync on if you used `[MTLCommandBuffer presentDrawable:]`.  AFAIK, MoltenVK always uses `[MTLDrawable present]` and has an option to enable or disable vsync during surface creation (but not after, annoyingly).  From the above comment, it sounds like you might not currently be requesting vsync from MoltenVK?  If so, doing this should solve the issue for people running 60fps on 60hz displays on Ventura.

Metal also has a [`[MTLDrawable presentAfterMinimumDuration:]`](https://developer.apple.com/documentation/metal/mtldrawable/2806859-presentafterminimumduration?language=objc) method, which will allow you to driver-enforce refresh rates that are even fractions of the display's refresh rate (e.g. 30fps on a 60hz display or 60fps on a 120hz display).  If you attempt to use this to e.g. enforce 60fps on a 144hz display, you'll end up with the highest refresh rate that's lower than what you requested and also an even fraction of the display refresh rate (in this case, 48fps), which is kind of annoying.  AFAIK, MoltenVK does not currently expose this.  If you're fullscreen on a VRR display, this is the recommended way to keep an even cadence on your presentation, and [Apple has a WWDC presentation on doing this](https://developer.apple.com/videos/play/wwdc2021/10147/).

Finally, Metal has a [`[MTLDrawable presentAtTime:]`](https://developer.apple.com/documentation/metal/mtldrawable/1470282-presentattime?language=objc), which allows you to request a specific time to present (units are the same as [`CACurrentMediaTime()`](https://developer.apple.com/documentation/quartzcore/1395996-cacurrentmediatime?language=objc), which is `mach_absolute_time()` / `CLOCK_UPTIME_RAW` converted to seconds).  This one's a pain because you have to estimate when the GPU will be done processing frames.  The [`[MTLCommandBuffer GPUEndTime]`](https://developer.apple.com/documentation/metal/mtlcommandbuffer/1639926-gpuendtime?language=objc) marker can help with this, but depending on whether your application is in borderless fullscreen or not (aka whether the thing that will be consuming your frame is the compositor or the display), the difference between the GPU finishing rendering and the earliest possible present time seems to change, at least on my Intel Mac.  You can compare your requested time to [`[MTLDrawable presentedTime]`](https://developer.apple.com/documentation/metal/mtldrawable/2806855-presentedtime?language=objc) to see how you're doing.  MoltenVK currently does not expose this, `GPUEndTime`, or `presentedTime`.

**Comment by riperiperi** [comment]
We're using MoltenVK, so it is handling all of these aspects based on requested Vulkan presenation and extensions. Trying to write the display sync will probably have it overwritten by MVK. `[MTLDrawable presentAtTime:]` is probably used by the `VK_GOOGLE_display_timing` extension, but there is no swap interval implementation. We can't skip to doing things with metal calls.

**Comment by skabning** [comment]
> @skabning what macOS version are you using?

Ventura 13.0.1 (the latest, I believe)

**Comment by Veemyu** [comment]
Great explanation, tellowkrinkle!
To the Ryujinx contributors, would you agree when implementing this, to also provide the ability to set vsync to a specific refresh rate while still respecting display timings? eg. 120 Hz display --> 120 Hz Vsync or 120 Hz display --> 60 Hz Vsync.
As M1 Devices are the main focus, it seems reasonable to use Ventura's capabilities.

**Comment by Stimpy7314** [comment]
U could try to enable this in the nvidia control panel: "Vulkan/OpenGL present method" Set it to "Prefer Layered on DXGI Swapchain" gsync, multiplane overlay, fso, hdr should work properly on vulkan/opengl games now.

**Comment by Veemyu** [comment]
Upstreaming is going well, and full versions of Ryujinx can be built now.
See Issues #4371 for Build instructions
The issue of VSync stuttering also spans across more than the new macOS platform. See Issues #4456 
The contributing developer would likely benefit Windows & Linux as well.
Now is the right time for the experts to shine @TellowKrinkle

**Comment by gdkchan** [comment]
I think the macOS  VSync issue was already fixed on #4379.

**Comment by Veemyu** [comment]
There still seem to be problems with VSync on macOS.
30 FPS - Pokémon BDSP is not smooth and has awful frame pacing.
If I turn VSync off, it can reach 200 FPS, so it is not a performance Bottleneck.
The same goes for Super Mario Odyssey. 
I'll test this further, also with ProMotion turned off, I hope it will help.
But alas, if it can't sync right because it doesn't get the REAL refresh rate of the Display as discussed above it will naturally look and feel stuttery.

Hardware:

MacBook Pro 2021 
M1 Pro 8/14
16 GB Ram
512 GB SSD

**Comment by Silent-Remux** [comment]
> I think the macOS VSync issue was already fixed on #4379.

Does this fix it for Windows users as well?

**Comment by riperiperi** [comment]
This fixes a specific issue where host vsync was never enabled on Avalonia. It does not fix any issues with presentation timing.

**Comment by riperiperi** [comment]
I've already explained the issue above. A lot of platform specific work needs to be put in to fix this since vulkan is very bad with it, so you might see a Windows only fix before you see a macos one, or vice versa.

**Comment by gdkchan** [comment]
> There still seem to be problems with VSync on macOS. 30 FPS - Pokémon BDSP is not smooth and has awful frame pacing. If I turn VSync off, it can reach 200 FPS, so it is not a performance Bottleneck. The same goes for Super Mario Odyssey. I'll test this further, also with ProMotion turned off, I hope it will help. But alas, if it can't sync right because it doesn't get the REAL refresh rate of the Display as discussed above, it will naturally look and feel stuttery.
> 
> Hardware:
> 
> MacBook Pro 14 2021 M1 Pro 8/14 16 GB Ram 512 GB SSD

I tested it here and it improved. Here is the comparison on my MacBook Air (2020 model):
Before:

https://user-images.githubusercontent.com/5624669/221981769-6472de9c-8fde-4587-9e7c-51f493751af3.mp4

After:

https://user-images.githubusercontent.com/5624669/221981814-6509e7f0-d5f4-4a91-a983-a5abb4ce5805.mp4

> Does this fix it for Windows users as well?

It fixed tearing on Windows with NVIDIA and VSync disabled on NVCP here (on Avalonia).

**Comment by amurgshere** [comment]
Thank you for this, I can definitely see noticeable improvements on “Guns, Gore and Cannoli” 1 and 2 along with many other scrolling games.

**Comment by Wiredframe** [comment]
I built the latest version and noticed it's indeed very smooth now, but only if I disable ProMotion (120fps) and set it to 60fps.

**Comment by aqxa1** [comment]
It's still broken for me on Linux. Some workarounds I've found for a HFR VRR/Freesync monitor with Sway (Wayland) are listed below. To get 1% lows/average fps etc, run `mangohud` with `MANGOHUD_CONFIG=output_dir=<dir>` then press Shift+F2 in game.

Disable built-in VSync in all cases as it's broken, and Wayland currently enforces external VSync anyway:
- Fixed FPS games (i.e. run at locked FPS and slow down rather than drop frames). 
   - Lock framerate to game framerate with MangoHUD
  - `MANGOHUD_CONFIG=fps_limit=60 <ryujinx command>` 

- Variable FPS games 
    - Workaround 1
         - Lower monitor refresh as close to average frame rate as possible while still keeping VRR enabled (I had to make a custom EDID to lower the minimum to 35hz to get VRR at 60hz). Preferably it should be as close to 1% lows, but that might be too low (it's a tradeoff)
         - A better choice if you want high framerates and to minimise input lag and can tolerate a bit of frame time variance (VRR helps here)
    -   Workaround 2
        -  Run with gamescope and limit to 1% lows (test with MANGOHUD) or as low as you can tolerate
        -  With a 1440p monitor (change 1440 to match your monitor's vertical resolution)
            -  `gamescope -h 1440 -H 1440 -r <fps limit> <ryujinx command>`
        -  Note: Steam Deck's built in frame limiter is the same as using `gamescope`, but since it doesn't support VRR, make sure the frame rate matches the refresh rate (or divides cleanly e.g. 30fps in 60hz mode)
        -  Unfortunately, this method increases input lag (`gamescope's` frame limiter is known to have issues here)
