### ISSUE TITLE
Audio latency on Linux with AMD GPU 

### ISSUE THREAD

**Issue by tommy-sorce** [Ryujinx/Ryujinx#5099]
### Description of the issue

There is big audio delay when playing fire emblem three houses 

### Reproduction steps

Play with hardware listed below 

### Log file

[Ryujinx_1.1.819_2023-05-25_13-48-59.log.txt](https://github.com/Ryujinx/Ryujinx/files/11565700/Ryujinx_1.1.819_2023-05-25_13-48-59.log.txt)

### OS

Ubuntu 23.04

### Ryujinx version

1.1.819

### Game version

1.2

### CPU

I5 4670k 

### GPU

Radeon R7 260x 

### RAM

8 GB DDR3 2400Mhz 

### List of applied mods

Non

### Additional context?

XMP enabled 
4.0 GHz overclock

**Comment by d07434b2c08f** [comment]
I'm having bad audio latency on Linux as well, in any game. It starts off fine, then gradually desyncs from the video more and more as I keep playing. I can pause the emulation for a few seconds and then resume to reset the latency, but doing that every 5 minutes is really irritating.

I don't think the problem is my GPU (RX 6700 XT) though, since this doesn't happen on Windows.

**Comment by rassoc** [comment]
Seeing the same on MK8DX with the SDL audio backend. But switching the setting to OpenAL fixes it entirely. No more audio desync even after an hour long session.

**Comment by AlexFolland** [comment]
Confirming that the workaround of using OpenAL solves the problem, also on Linux.  Maybe it would be better to use OpenAL by default if it's available on Linux.

**Comment by brunoalcruz** [comment]
Pessoal, a latencia que tem no audio usando o ryujinx foi resolvida usando a biblioteca OpenAL nas opções de audio que tem dentro do emualdor, pois fiz a instalação do Yuzu via flatpak no meu Pop OS e verifiquei que nçao tinha nenhum atraso no som de qualquer game e fui nas configurações para ver e vi que o Yuzu usa o OpenAL como saida de audio e o ryujinx usa SDL por padrão. Agora é só mudar para OpenAL que vai ser tudo resolvido, mas naço se esqueçam de manter seu emulador sempre atualizado.

Guys, the latency in the audio using ryujinx was resolved using the OpenAL library in the audio options within the emulator, as I installed Yuzu via flatpak on my Pop OS and verified that there was no delay in the sound of any game and went to the settings to see and saw that Yuzu uses OpenAL as audio output and ryujinx uses SDL by default. Now just switch to OpenAL and everything will be resolved, but don't forget to keep your emulator up to date.

**Comment by Dalcinrafa** [comment]
I'm on Fedora 40, and even with OpenAL I still have this issue. Every 2 minutes i have to pause to sync the audio. On Yuzu that simply doesn't happen, but Yuzu was discontinued and I can't play Paper Mario TTYD on Yuzu. Help appreciated!!

**Comment by Turmaxx** [comment]
Does any one have a fix for this yet?

**Comment by CatMow** [comment]
to fix audio latency

in game, press f5 to pause. screen should freeze. **wait for audio to stop**, then unfreeze by pressing f5

**Comment by Turmaxx** [comment]
Is this a temporary or permanent fix?

**Comment by Ammar-Sadaoui** [comment]
are you using wayland ?

**Comment by Turmaxx** [comment]
yes I am.

**Comment by Ammar-Sadaoui** [comment]
> yes I am.

there chance this xwayland fault try x11 and see if you still have this issues or not

**Comment by TSRBerry** [comment]
Wayland has nothing to do with this. On Linux you should make sure to use the OpenAL audio backend as that doesn't desync as often.

Of course that we are having desync issues with other audio backends on Linux is still an issue.

**Comment by CatMow** [comment]
> Is this a temporary or permanent fix?

temporary. you may have to do it even hour or so depending on how much your audio desyncs

**Comment by Drikanis** [comment]
Getting this as well, NVidia GPU (so this is not specific to Radeon) on Xorg (so not an issue with wayland).
Debian 12 running Ryujinx 1.1.1401, using Pipewire as the sound system.
Both SDL2 and OpenAL exhibit the issue and SoundIO doesn't output any audio at all.
I left it running on a title screen for 20 or so minutes and the delay slowly increased to over 8 seconds.

**Comment by Drikanis** [comment]
Did some more experimentation and found that setting the following environment variable seems to do the trick:
```
PULSE_LATENCY_MSEC=83
```
Not only does the audio now stay in sync, but it eliminates the crackling I was experiencing as well!

In my case I launch Ryujinx with a desktop shortcut, so I edited it like so:
```
[Desktop Entry]
Type=Application
Name=Ryujinx
Exec=env PULSE_LATENCY_MSEC=83 gamemoderun /home/drikanis/Games/ryujinx/publish/Ryujinx
Categories=Game
```
