### ISSUE TITLE
[Bug] Unable to play Stardew Valley because Software Keyboard prompt will not close

### ISSUE THREAD

**Issue by evanpaul14** [Ryujinx/Ryujinx#5625]
### Description of the issue

When creating an new game you have to set a Name, Farm Name, and Favorite Thing.  Clicking on one will open the software keyboard but after typing something in and pressing ok the prompt will close and open again on repeat. 

### Reproduction steps

Create new game and try to set a name.

### Log file

[Ryujinx_1.1.1002_2023-08-29_17-26-09.log](https://github.com/Ryujinx/Ryujinx/files/12470514/Ryujinx_1.1.1002_2023-08-29_17-26-09.log)

### OS

MacOS

### Ryujinx version

1.1.1002

### Game version

1.5.4.2

### CPU

M1

### GPU

M1

### RAM

8 GB

### Additional context?

https://github.com/Ryujinx/Ryujinx/assets/120766197/60585111-8b44-4215-b018-8440e04dfda6

**Comment by music-discussion** [comment]
Same issue here. The thing is that it just started happening one update.

**Comment by TSRBerry** [comment]
>started happening one update

If you could figure out which version caused this issue we will be able to fix this quite quickly.

**Comment by music-discussion** [comment]
Well actually now that I am looking, it seems like it was fixed and then broken again. As version 1.33 works fine but the versions after it are broken.

**Comment by evanpaul14** [comment]
It works with my xbox controller but not the keyboard controller.On Sep 5, 2023, at 11:19 AM, music-discussion ***@***.***> wrote:
Well actually now that I am looking, it seems like it was fixed and then broken again. As version 1.33 works fine but the versions after it are broken.

**Comment by music-discussion** [comment]
> It works with my xbox controller but not the keyboard controller.

That’s interesting

**Comment by music-discussion** [comment]
I think I have figured out the issue. The issue is that Ryujinx does not stop inputs when you open the keyboard, the inputs are still being pressed in the background. For some reason, the Stardew Valley Developers decided to check every frame whether or not you are pressing A on a textbox and pop up the keyboard. This makes sense because with an xbox controller, you are able to control the background while the keyboard is popped up. Another thing is, if you hold A while on the text box, the console spams, however if you let go, the console comes to a halt.

**Comment by StanfordHu** [comment]
Hi, I am currently still experiencing this problem. What is the solution that you've found?
